### PR TITLE
Feature/new gradle build

### LINKED ISSUE #23: CI optimization
In the future, it would be nice to optimize even more the CI process. The current pipeline shares Gradle caches between jobs, to minimize eventual duplicated Gradle file generation, but not the build artifacts, that are re-created for each job.

Sharing build artifacts between jobs would minimize CI execution time. For example, using the artifact sharing action given by GitHub, or by other ways. Someone could deepen this aspect.

### PR DESCRIPTION
**Pull request by corinz97**
More details can be found [here](https://github.com/scalaquest/PPS-19-ScalaQuest/issues/23#issuecomment-764794485)

### CODE REVIEW

**Comment by corinz97** [comment]
I suggest to squash commits

**Comment by maldins46** [comment]
Sorry for the intrusion on your PR @corinz97 😅 
I've made some minor name refactoring in the CI, including the support for the future GitFlow-based structure (#34)

> I suggest to squash commits

Agree. We should merge these modifications in `main` with the **squash and merge** feature.

**Review by ThomasAngeliniUnibo — APPROVED** [review]
Yes, great time saver

**Comment by corinz97** [comment]
I've written also an `if ` on job condition, in order to skip the entire job without either comment. Otherwise, it would enter the job, skip the steps and flagging green but it doesn't do anything concretely

**Pull request merged**
