### PR TITLE
Feature/refactoring prolog parser

### PR DESCRIPTION
**Pull request by lippo97**
This pull request contains some things @francescogorini and I did lately. I will try to summarize them here.

* We introduced a new concept called Dictionary (it's just a temporary name) that should generate both prolog code and the data needed by the Resolver, to avoid data duplication.
* We changed a lot the Prolog base grammar, refactoring duplicated code and making it much easier for the dictionary to generate code for verbs (and in the future for adjectives and items).
* We refactored the existing Scalog dsl and introduced a new dsl extractor that makes matching prolog compound terms easier.
* Now verbs are distinguished not only by their name, but for the preposition they are used with too.
* We updated all the existing tests to include changes.

Little note for @maldins46, @ThomasAngeliniUnibo and @corinz97: I had to disable this test because i couldn't understand how to make it work. If you can fix this and then accept the pr.

https://github.com/scalaquest/PPS-19-ScalaQuest/blob/b26e13c83a9605a902b3cab4fcd4a74c907f768a/core/src/test/scala/io/github/scalaquest/core/pipeline/resolver/ResolverTest.scala#L15-L36

### CODE REVIEW

**Comment by maldins46** [comment]
Nice! We will review the test for the scrum meeting of tomorrow, or early if we can

**Comment by maldins46** [comment]
Pro tip: you can refer to all of us with the tag @scalaquest/team-1 🤓

**Comment by lippo97** [comment]
That would mean we accept you being the team number 1.

Mindblow

**Comment by maldins46** [comment]
Solved! Initially, the intransitive test was using the `Open` action, which is not intransitive actually. I used the `Go(North)` action, and add it into the initial test state.

**Comment by maldins46** [comment]
This PR partially solves #48

**Review by maldins46 — APPROVED** [review]
Smoothly functional and Prologish

Functional

**Pull request merged**
